[package]
name = "mandala"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", features = ["loaded", "debug"] }
ash-window = "0.13.0"
log = "0.4.22"
simplelog = "0.12.2"
winit = "0.30.3"


